### ISSUE TITLE
Not actually deploying?

### ISSUE THREAD

**Issue by alessandrotesoro** [stephenharris/grunt-wp-deploy#14] opened 2014-10-30 17:36 UTC
Hi there,

I'm not able to actually see any deployment, my svn repo is a new empty repo, after using grunt, and confirming everything was fine, nothing was actually commit, it just created a folder 1.0.0 into the "tag" folder. 

The output is 
```
Running "wp_deploy:deploy" (wp_deploy) task
Checking out http://plugins.svn.wordpress.org/wp-restaurant-manager
Check out complete.
Clearing trunk.
Copying deploy/ to /tmp/wp-restaurant-manager/trunk/
[?] Are you sure you want to commit "1.0.0"? Yes
Committing to trunk
Password for 'alessandro.tesoro': 
Copying to tag
Committing tag

Done, without errors.
```

But again, no files are actually being commit? Am i doing anything wrong?

**Comment by helgatheviking** [comment] 2015-08-21 22:15
I can confirm that the new version *does* finally get the build folder copied over to the trunk of the temporary directory set via the `tmp_dir` option. However, I'm still stuck getting the trunk copied into the tag. 

```
Committing 1.7.6 to trunk

Copying 1.7.6to tag
Tagging 1.7.6

Warning: Failed to comit tag: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "cd D:/SVN/radio-buttons-for-taxonomies/tags/1.7.6
 svn commit --force-interactive --username="helgatheviking" -m "Tagging 1.7.6""
The system cannot find the path specified.
 Use --force to continue.
```

When I do this by hand, I usually use `svn mkdir`. Would you be able to add that? 

```
								//Copy to tag
								grunt.log.writeln( 'Creating ' + new_version + ' tag');
								var cmd = exec( "svn mkdir "+svnpath+"/tags/"+new_version, {}, function( error, stdout, stderr) {
									if (error !== null) {
										grunt.fail.warn( 'Failed to create folder for tag: ' + error );
									}
									grunt.log.writeln( 'Copying ' + new_version + ' to tag');
									var cmd = exec( "cd "+svnpath+"\n svn copy trunk/ tags/"+new_version, {}, function( error, stdout, stderr) {
										if (error !== null) {
											grunt.fail.warn( 'Failed to copy to tag: ' + error );
										}
										grunt.warn(error + ' ' + stdout + ' ' + stderr);
										//Commit tag
										grunt.log.writeln( tagCommitMsg + "\n" );
										var cmd = exec( 'cd '+svnpath+'/tags/'+new_version+'\n svn commit --force-interactive --username="'+svnuser+'" -m "'+tagCommitMsg+'"', {}, function( error, stdout, stderr) {
					
											if (error !== null) {
												grunt.fail.warn( 'Failed to commit tag: ' + error );
											}
											
											//Commit assets
											if( options.assets_dir ){
												
												grunt.log.writeln( assetCommitMsg + "\n" );
			
												cmd = "cd "+svnpath+"/assets; pwd;";
												cmd += "svn status | grep -v '^.[ \t]*\\..*' | grep '^?' | awk '{print $2}' | xargs svn add;"; //Add new files
												cmd += "svn status | grep -v '^.[ \t]*\\..*' | grep '^!' | awk '{print $2}' | xargs svn delete;"; //Remove missing files
												cmd += 'cd '+svnpath+'/assets\n svn commit --force-interactive --username="'+svnuser+'" -m "'+assetCommitMsg+'"';
												
												var cmd = exec( cmd,{}, function(error, stdout, stderr) {
													if (error !== null) {
														grunt.fail.warn( 'Failed to commit to assets: ' + error );
													}
													done();
												} );
											}else{
												done();
											}
										});
									}); //Copy to  tag

								}); //create tag folder
```

Unfortunately, that doesn't seem to resolve my issues, but does get me a step closer.

**Comment by stephenharris** [comment] 2015-09-01 21:46
@helgatheviking So `svn mkdir` resolves the *The system cannot find the path specified* error? What are the other issues that you're running into?

**Comment by helgatheviking** [comment] 2015-09-04 00:31
I'll have to test it again, but the trunk wasn't getting copied to the tag.

**Comment by marcochiesi** [comment] 2015-11-21 11:30
Hi there,
I am experiencing similar problems on my Win7 machine. In my case my trunk was not populated from my build directory, even if there was no error reported, and at the same time the assets directory was correctly copied. After some debugging I found that the problem was depending on subprocesses running in an asynchronous way, so that the trunk clearing was made after the copy from build directory to trunk, even if it was called before inside the code.
I was able to workaround it by using the [`execSync`](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) call, which waits for the subprocess to end before proceeding.
So I added a
`var execSync = require('child_process').execSync;`
and replaced all `exec` calls without a callback with `execSync` (having the subsequent code inside the callback is an alternative way to synchronize).
With this modification my trunk was correctly populated with files, but unfortunately it's only a step closer, and not the final solution, because svn commiting still doesn't work.
It looks like Win doesn't like multiple commands (separated by `\n` or `;`) in a single command line. A workaround for this may be avoid using the `cd` commands prepended to the `svn` commands, and use instead the `cwd` option of the `exec` / `execSync` calls to set the current directory.

Note: a recent nodejs version is needed for having `execSync` (I had to update my old install).

When I'll have time I'll try to do some more testing.

**Comment by helgatheviking** [comment] 2015-11-23 08:14
I have to admit that I gave up and am now using the [deployer service](http://deployer.edwinapp.com/). I just don't know enough about grunt or svn to figure out what was going wrong.

**Comment by stephenharris** [comment] 2015-11-23 17:49
@marcochiesi  - I've been thinking it should be using grunt.util.spawn - which allows us to specify a directory. Not sure how that compares to execSync.

**Comment by marcochiesi** [comment] 2015-11-23 18:08
Hi there,
eventually... I made it! I had to do a certain amount of modifications, but at the end I was able to run the script on Windows. I would be glad to send a pull request and further info, if you are going to merge it in the codebase. Thanks.

**Comment by stephenharris** [comment] 2015-11-23 22:41
Please, I'm sure @helgatheviking would be grateful too.

**Comment by helgatheviking** [comment] 2015-11-24 04:38
Yeah, that'd be cool to actually see it work for me! But, deployer is pretty sweet as an alternative.

**Comment by stephenharris** [comment] 2016-07-18 21:29
Closing this as I think all necessary changes have been made to make this compatible with Windows, but I must stress I've not tested this on a Windows machine, so feel free to re-open.

**Closed by stephenharris** 2016-07-18 21:29 UTC
